app/base/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'accounts/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'accounts/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        # Check usename exists
        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Username already registered',
                                    success=False,
                                    form=create_account_form)

        # Check email exists
        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Email already registered', 
                                    success=False,
                                    form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'accounts/register.html', 
                                msg='User created please <a href="/login">login</a>', 
                                success=True,
                                form=create_account_form)

    else:
        return render_template( 'accounts/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('page-403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('page-403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('page-500.html'), 500

app/base/templates/accounts/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="d-n@sm- peer peer-greed h-100 pos-r bgr-n bgpX-c bgpY-c bgsz-cv" style='background-image: url("/static/assets/static/images/bg.jpg")'>
        <div class="pos-a centerXY">
          <div class="bgc-white bdrs-50p pos-r" style="width: 120px; height: 120px;">
            <img class="pos-a centerXY" src="/static/assets/static/images/logo.png" alt="">
          </div>
        </div>
      </div>
      <div class="col-12 col-md-4 peer pX-40 pY-80 h-100 bgc-white scrollable pos-r" style="min-width: 320px;">

        <h3 class="fw-300 c-grey-900 mB-40">
          <a target="_blank" rel="noopener noreferrer" 
             href="https://appseed.us/admin-dashboards/flask-dashboard-adminator">Flask Dashboard Adminator</a> - Login
        </h3>

        {% if msg %}
            <h4 class="fw-300 c-grey-900 mB-40">{{ msg | safe }}</h4>
        {% else %}
            <p class="fw-300 c-grey-900 mB-40">
              Use default credentials: <strong>test / pass</strong>
            </p>
        {% endif %}

        <form method="post" action="">

          {{ form.hidden_tag() }}

          <div class="form-group">
            <label class="text-normal text-dark">Username</label>
            {{ form.username(placeholder="Username", class="form-control") }}
          </div>

          <div class="form-group">
            <label class="text-normal text-dark">Password</label>
            {{ form.password(placeholder="Password", class="form-control", type="password") }}
          </div>

          <div class="form-group">
            <div class="peers ai-c jc-sb fxw-nw">
              <div class="peer">
                <button type="submit" name="login" class="btn btn-primary">Login</button>
                
                &nbsp; &nbsp; 
                <span class="text-small font-weight-semibold">Not a member?</span> 
                <a href="{{ url_for('base_blueprint.register') }}" class="text-black text-small">Register</a>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>  

{% endblock content %}

app/base/templates/accounts/register.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Register {% endblock title %}

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

      <div class="peer peer-greed h-100 pos-r bgr-n bgpX-c bgpY-c bgsz-cv" style='background-image: url("/static/assets/static/images/bg.jpg")'>
        <div class="pos-a centerXY">
          <div class="bgc-white bdrs-50p pos-r" style="width: 120px; height: 120px;">
            <img class="pos-a centerXY" src="/static/assets/static/images/logo.png" alt="">
          </div>
        </div>
      </div>
      <div class="col-12 col-md-4 peer pX-40 pY-80 h-100 bgc-white scrollable pos-r" style="min-width: 320px;">
      
        <h3 class="fw-300 c-grey-900 mB-40">
          <a target="_blank" rel="noopener noreferrer" 
             href="https://appseed.us/admin-dashboards/flask-dashboard-adminator">Flask Dashboard Adminator</a> - Register
        </h3>

        {% if msg %}
            <h4 class="fw-300 c-grey-900 mB-40">{{ msg | safe }}</h4>
        {% else %}
            <p class="fw-300 c-grey-900 mB-40">
              Add your credentials 
            </p>
        {% endif %}

        <form method="post" action="">

          {{ form.hidden_tag() }}

          <div class="form-group">
            <label class="text-normal text-dark">Username</label>
            {{ form.username(placeholder="Username", class="form-control") }}
          </div>
          
          <div class="form-group">
            <label class="text-normal text-dark">eMail Address</label>
            {{ form.email(placeholder="eMail Address", class="form-control") }}
          </div>

          <div class="form-group">
            <label class="text-normal text-dark">Password</label>
            {{ form.password(placeholder="Password", class="form-control", type="password") }}
          </div>

          <div class="form-group">
            <button type="submit" name="register" class="btn btn-primary">Register</button> 

            &nbsp; &nbsp;
            <span class="text-small font-weight-semibold">Have and account?</span>
            <a href="{{ url_for('base_blueprint.login') }}" class="text-black text-small">Login</a>    
          </div>

        </form>
      </div>

{% endblock content %}

app/base/templates/includes/footer.html
  <!-- ### $App Screen Footer ### -->
  <footer class="bdT ta-c p-30 lh-0 fsz-sm c-grey-600">
    <span>
      &copy; Colorlib. 
      <a target="_blank" rel="noopener noreferrer" href="https://appseed.us/admin-dashboards/flask-dashboard-adminator">Flask Dashboard Adminator</a> 
      - coded by <a target="_blank" rel="noopener noreferrer" href="https://appseed.us">AppSeed</a>. 
    </span>
  </footer>

app/base/templates/includes/navigation.html
    <!-- ### $Topbar ### -->
    <div class="header navbar">
      <div class="header-container">
        <ul class="nav-left">
          <li>
            <a id="sidebar-toggle" class="sidebar-toggle" href="javascript:void(0);">
              <i class="ti-menu"></i>
            </a>
          </li>
          <li class="search-box">
            <a class="search-toggle no-pdd-right" href="javascript:void(0);">
              <i class="search-icon ti-search pdd-right-10"></i>
              <i class="search-icon-close ti-close pdd-right-10"></i>
            </a>
          </li>
          <li class="search-input">
            <input class="form-control" type="text" placeholder="Search...">
          </li>
        </ul>
        <ul class="nav-right">
          <li class="notifications dropdown">
            <span class="counter bgc-red">3</span>
            <a href="" class="dropdown-toggle no-after" data-toggle="dropdown">
              <i class="ti-bell"></i>
            </a>

            <ul class="dropdown-menu">
              <li class="pX-20 pY-15 bdB">
                <i class="ti-bell pR-10"></i>
                <span class="fsz-sm fw-600 c-grey-900">Notifications</span>
              </li>
              <li>
                <ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
                  <li>
                    <a href="" class="peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100">
                      <div class="peer mR-15">
                        <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt="">
                      </div>
                      <div class="peer peer-greed">
                        <span>
                          <span class="fw-500">John Doe</span>
                          <span class="c-grey-600">liked your <span class="text-dark">post</span>
                          </span>
                        </span>
                        <p class="m-0">
                          <small class="fsz-xs">5 mins ago</small>
                        </p>
                      </div>
                    </a>
                  </li>
                  <li>
                    <a href="" class="peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100">
                      <div class="peer mR-15">
                        <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/2.jpg" alt="">
                      </div>
                      <div class="peer peer-greed">
                        <span>
                          <span class="fw-500">Moo Doe</span>
                          <span class="c-grey-600">liked your <span class="text-dark">cover image</span>
                          </span>
                        </span>
                        <p class="m-0">
                          <small class="fsz-xs">7 mins ago</small>
                        </p>
                      </div>
                    </a>
                  </li>
                  <li>
                    <a href="" class="peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100">
                      <div class="peer mR-15">
                        <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/3.jpg" alt="">
                      </div>
                      <div class="peer peer-greed">
                        <span>
                          <span class="fw-500">Lee Doe</span>
                          <span class="c-grey-600">commented on your <span class="text-dark">video</span>
                          </span>
                        </span>
                        <p class="m-0">
                          <small class="fsz-xs">10 mins ago</small>
                        </p>
                      </div>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="pX-20 pY-15 ta-c bdT">
                <span>
                  <a href="" class="c-grey-600 cH-blue fsz-sm td-n">View All Notifications <i class="ti-angle-right fsz-xs mL-10"></i></a>
                </span>
              </li>
            </ul>
          </li>
          <li class="notifications dropdown">
            <span class="counter bgc-blue">3</span>
            <a href="" class="dropdown-toggle no-after" data-toggle="dropdown">
              <i class="ti-email"></i>
            </a>

            <ul class="dropdown-menu">
              <li class="pX-20 pY-15 bdB">
                <i class="ti-email pR-10"></i>
                <span class="fsz-sm fw-600 c-grey-900">Emails</span>
              </li>
              <li>
                <ul class="ovY-a pos-r scrollable lis-n p-0 m-0 fsz-sm">
                  <li>
                    <a href="" class="peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100">
                      <div class="peer mR-15">
                        <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/1.jpg" alt="">
                      </div>
                      <div class="peer peer-greed">
                        <div>
                          <div class="peers jc-sb fxw-nw mB-5">
                            <div class="peer">
                              <p class="fw-500 mB-0">John Doe</p>
                            </div>
                            <div class="peer">
                              <small class="fsz-xs">5 mins ago</small>
                            </div>
                          </div>
                          <span class="c-grey-600 fsz-sm">
                            Want to create your own customized data generator for your app...
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <a href="" class="peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100">
                      <div class="peer mR-15">
                        <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/2.jpg" alt="">
                      </div>
                      <div class="peer peer-greed">
                        <div>
                          <div class="peers jc-sb fxw-nw mB-5">
                            <div class="peer">
                              <p class="fw-500 mB-0">Moo Doe</p>
                            </div>
                            <div class="peer">
                              <small class="fsz-xs">15 mins ago</small>
                            </div>
                          </div>
                          <span class="c-grey-600 fsz-sm">
                            Want to create your own customized data generator for your app...
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <a href="" class="peers fxw-nw td-n p-20 bdB c-grey-800 cH-blue bgcH-grey-100">
                      <div class="peer mR-15">
                        <img class="w-3r bdrs-50p" src="https://randomuser.me/api/portraits/men/3.jpg" alt="">
                      </div>
                      <div class="peer peer-greed">
                        <div>
                          <div class="peers jc-sb fxw-nw mB-5">
                            <div class="peer">
                              <p class="fw-500 mB-0">Lee Doe</p>
                            </div>
                            <div class="peer">
                              <small class="fsz-xs">25 mins ago</small>
                            </div>
                          </div>
                          <span class="c-grey-600 fsz-sm">
                            Want to create your own customized data generator for your app...
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="pX-20 pY-15 ta-c bdT">
                <span>
                  <a href="/email.html" class="c-grey-600 cH-blue fsz-sm td-n">View All Email <i class="fs-xs ti-angle-right mL-10"></i></a>
                </span>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="" class="dropdown-toggle no-after peers fxw-nw ai-c lh-1" data-toggle="dropdown">
              <div class="peer mR-10">
                <img class="w-2r bdrs-50p" src="https://randomuser.me/api/portraits/men/10.jpg" alt="">
              </div>
              <div class="peer">
                <span class="fsz-sm c-grey-900">
                  {{ current_user.user }}
                </span>
              </div>
            </a>
            <ul class="dropdown-menu fsz-sm">
              <li>
                <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                  <i class="ti-settings mR-10"></i>
                  <span>Setting</span>
                </a>
              </li>
              <li>
                <a href="" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                  <i class="ti-user mR-10"></i>
                  <span>Profile</span>
                </a>
              </li>
              <li>
                <a href="/email.html" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                  <i class="ti-email mR-10"></i>
                  <span>Messages</span>
                </a>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <a href="{{ url_for('base_blueprint.logout') }}" class="d-b td-n pY-5 bgcH-grey-100 c-grey-700">
                  <i class="ti-power-off mR-10"></i>
                  <span>Logout</span>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>

app/base/templates/includes/scripts.html
<!-- NOT IMPLEMENTED -->

app/base/templates/includes/sidebar.html
      <!-- #Left Sidebar ==================== -->
      <div class="sidebar">
        <div class="sidebar-inner">
          <!-- ### $Sidebar Header ### -->
          <div class="sidebar-logo">
            <div class="peers ai-c fxw-nw">
              <div class="peer peer-greed">
                <a class="sidebar-link td-n" href="https://appseed.us/admin-dashboards/flask-dashboard-adminator">
                  <div class="peers ai-c fxw-nw">
                    <div class="peer">
                      <div class="logo">
                        <img src="/static/assets/static/images/logo.png" alt="">
                      </div>
                    </div>
                    <div class="peer peer-greed">
                      <h5 class="lh-1 mB-0 logo-text">Adminator</h5>
                    </div>
                  </div>
                </a>
              </div>
              <div class="peer">
                <div class="mobile-toggle sidebar-toggle">
                  <a href="" class="td-n">
                    <i class="ti-arrow-circle-left"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>

          <!-- ### $Sidebar Menu ### -->
          <ul class="sidebar-menu scrollable pos-r">
            <li class="nav-item mT-30 actived">
              <a class="sidebar-link" href="/">
                <span class="icon-holder">
                  <i class="c-blue-500 ti-home"></i>
                </span>
                <span class="title">Dashboard</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="sidebar-link" href="/email.html">
                <span class="icon-holder">
                  <i class="c-brown-500 ti-email"></i>
                </span>
                <span class="title">Email</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="sidebar-link" href="/compose.html">
                <span class="icon-holder">
                  <i class="c-blue-500 ti-share"></i>
                </span>
                <span class="title">Compose</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="sidebar-link" href="/calendar.html">
                <span class="icon-holder">
                  <i class="c-deep-orange-500 ti-calendar"></i>
                </span>
                <span class="title">Calendar</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="sidebar-link" href="/chat.html">
                <span class="icon-holder">
                  <i class="c-deep-purple-500 ti-comment-alt"></i>
                </span>
                <span class="title">Chat</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="sidebar-link" href="/charts.html">
                <span class="icon-holder">
                  <i class="c-indigo-500 ti-bar-chart"></i>
                </span>
                <span class="title">Charts</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="sidebar-link" href="/forms.html">
                <span class="icon-holder">
                  <i class="c-light-blue-500 ti-pencil"></i>
                </span>
                <span class="title">Forms</span>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="sidebar-link" href="/ui.html">
                <span class="icon-holder">
                    <i class="c-pink-500 ti-palette"></i>
                  </span>
                <span class="title">UI Elements</span>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="dropdown-toggle" href="javascript:void(0);">
                <span class="icon-holder">
                  <i class="c-orange-500 ti-layout-list-thumb"></i>
                </span>
                <span class="title">Tables</span>
                <span class="arrow">
                  <i class="ti-angle-right"></i>
                </span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a class="sidebar-link" href="/basic-table.html">Basic Table</a>
                </li>
                <li>
                  <a class="sidebar-link" href="/datatable.html">Data Table</a>
                </li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="dropdown-toggle" href="javascript:void(0);">
                <span class="icon-holder">
                    <i class="c-purple-500 ti-map"></i>
                  </span>
                <span class="title">Maps</span>
                <span class="arrow">
                    <i class="ti-angle-right"></i>
                  </span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="/google-maps.html">Google Map</a>
                </li>
                <li>
                  <a href="/vector-maps.html">Vector Map</a>
                </li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="dropdown-toggle" href="javascript:void(0);">
                <span class="icon-holder">
                    <i class="c-red-500 ti-files"></i>
                  </span>
                <span class="title">Pages</span>
                <span class="arrow">
                    <i class="ti-angle-right"></i>
                  </span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a class="sidebar-link" href="/page-blank.html">Blank</a>
                </li>                 
                <li>
                  <a class="sidebar-link" href="/page-404.html">404</a>
                </li>
                <li>
                  <a class="sidebar-link" href="/page-500.html">500</a>
                </li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="dropdown-toggle" href="javascript:void(0);">
                <span class="icon-holder">
                  <i class="c-teal-500 ti-view-list-alt"></i>
                </span>
                <span class="title">Multiple Levels</span>
                <span class="arrow">
                  <i class="ti-angle-right"></i>
                </span>
              </a>
              <ul class="dropdown-menu">
                <li class="nav-item dropdown">
                  <a href="javascript:void(0);">
                    <span>Menu Item</span>
                  </a>
                </li>
                <li class="nav-item dropdown">
                  <a href="javascript:void(0);">
                    <span>Menu Item</span>
                    <span class="arrow">
                      <i class="ti-angle-right"></i>
                    </span>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <a href="javascript:void(0);">Menu Item</a>
                    </li>
                    <li>
                      <a href="javascript:void(0);">Menu Item</a>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="sidebar-link" href="{{ url_for('base_blueprint.logout') }}" >
                <span class="icon-holder">
                    <i class="ti-power-off mR-10"></i>
                  </span>
                <span class="title">Logout</span>
              </a>
            </li>            
          </ul>
        </div>
      </div>

app/base/templates/layouts/base-error.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <title>
      Flask Adminator - {% block title %}{% endblock %} | AppSeed
    </title>

    <link href="/static/assets/style.css" rel="stylesheet">

  </head>
  <body class="app">

    {% block content %}{% endblock content %}  
  
    <script type="text/javascript" src="/static/assets/vendor.js"></script>
    <script type="text/javascript" src="/static/assets/bundle.js"></script>
    
  </body>
</html>